pipeline:
  test:
    image: node:8-alpine
    environment:
      - NODE_ENV=production
      - API_URL=http://api.socialcrawler.jumpso.cool/api
    commands:
      - npm install
      - npm run build
  build:
    image: plugins/docker
    repo: registry.witsawa.com/socialcrawlerclient
    registry: registry.witsawa.com
    tags: latest
    dockerfile: dockerfile
    username: witsawa
    password: Witsawa122333
  deploy:
    image: peloton/drone-rancher
    url: http://rancher.jumpso.cool
    access_key: CA3127C7738B73D0607B
    secret_key: PN6Dm5r4dF2cMLVfDas3Yuvvew2MQPbS6FbsHGdt
    service: socialcrawler/client
    docker_image: registry.witsawa.com/socialcrawlerclient:latest
    confirm: true
branches: master